# Generated by Django 4.1.1 on 2024-01-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'VENDOR'), (1, 'CUSTOMER')], default=1),
        ),
    ]
