# Generated by Django 4.1.1 on 2024-01-01 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        ('customer', '0001_initial'),
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('description', models.TextField()),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('departure_time', models.DateTimeField()),
                ('arrival_location', models.CharField(max_length=255)),
                ('departure_location', models.CharField(max_length=255)),
                ('flight_name', models.CharField(max_length=255)),
                ('arrival_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('inflight_experience', models.JSONField(blank=True, default=dict, null=True)),
                ('duration', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('average_rating', models.PositiveIntegerField()),
                ('flight_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_image', to='coreapp.document')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_flight', to='vendor.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='FlightSeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('passenger_type', models.IntegerField()),
                ('seat_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FlightReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('review', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('review_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_review_flight', to='customer.customer')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_flight', to='flight.flight')),
            ],
        ),
        migrations.CreateModel(
            name='FlightPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('cabin', models.IntegerField()),
                ('baggage', models.IntegerField()),
                ('check_in', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_flight', to='flight.flight')),
                ('flight_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_pricing_flight', to='flight.flightseattype')),
            ],
        ),
        migrations.CreateModel(
            name='FlightFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('faq', models.JSONField(blank=True, default=dict, null=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_flight', to='flight.flight')),
            ],
        ),
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('booking_number', models.IntegerField()),
                ('quantity', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_booking_flight', to='customer.customer')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_flight', to='flight.flight')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
