# Generated by Django 4.1.1 on 2024-01-03 19:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightbooking',
            name='quantity',
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='ticket_quantity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='ticket_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=[], size=None),
            preserve_default=False,
        ),
    ]
