# Generated by Django 4.1.1 on 2024-01-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_flightbooking_confirm_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='confirm_booking',
        ),
    ]
