# Generated by Django 4.1.1 on 2024-01-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_remove_flight_confirm_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='average_rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
