# Generated by Django 4.1.1 on 2024-01-01 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        ('customer', '0001_initial'),
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('longitude', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('average_rating', models.PositiveIntegerField()),
                ('highlights', models.JSONField(blank=True, default=dict, null=True)),
                ('exclude', models.JSONField(blank=True, default=dict, null=True)),
                ('facilities', models.JSONField(blank=True, default=dict, null=True)),
                ('overview', models.TextField()),
                ('tour_type', models.JSONField(blank=True, default=dict, null=True)),
                ('latitude', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tour_name', models.CharField(max_length=255)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('travel_style', models.JSONField(blank=True, default=dict, null=True)),
                ('include', models.JSONField(blank=True, default=dict, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_tour', to='vendor.vendor')),
                ('tour_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_image', to='coreapp.document')),
            ],
        ),
        migrations.CreateModel(
            name='TourTicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('ticket_type', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('rule', models.JSONField(blank=True, default=dict, null=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_tour', to='tour.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('review', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('review_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_review_tour', to='customer.customer')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tour', to='tour.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('extra_price', models.JSONField(blank=True, default=dict, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fixed_price', models.JSONField(blank=True, default=dict, null=True)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_pricing_tour', to='tour.tourtickettype')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tour', to='tour.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('itinerary_image', models.ImageField(upload_to='')),
                ('day', models.CharField(max_length=30)),
                ('details', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_tour', to='tour.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('faq', models.JSONField(blank=True, default=dict, null=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_tour', to='tour.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('group_size', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('duration', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=255)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_tour', to='tour.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('booking_number', models.IntegerField()),
                ('star_date', models.DateTimeField()),
                ('total_adult', models.IntegerField(default=1)),
                ('total_child', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_tour', to='customer.customer')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_tour', to='tour.tour')),
            ],
        ),
    ]
