# Generated by Django 4.1.1 on 2024-01-03 18:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_tourbooking_adult_ticket_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourbooking',
            name='adult_ticket_type',
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='child_ticket_type',
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='total_adult',
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='total_child',
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='ticket_quantity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='ticket_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='booking_number',
            field=models.IntegerField(default=0),
        ),
    ]
