# Generated by Django 4.1.1 on 2024-01-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_remove_tourbooking_adult_ticket_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbooking',
            name='confirm_booking',
            field=models.BooleanField(default=False),
        ),
    ]
