# Generated by Django 4.1.1 on 2024-01-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_tour_location_alter_tour_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='average_rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
