# Generated by Django 4.1.1 on 2024-01-07 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_user_role'),
        ('tour', '0006_alter_tour_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touritinerary',
            name='itinerary_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_itinerary_image', to='coreapp.document'),
        ),
    ]
