# Generated by Django 4.1.1 on 2024-01-03 05:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatbooking',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boatbooking',
            name='total_day',
            field=models.IntegerField(default=0),
        ),
    ]
