# Generated by Django 4.1.1 on 2024-01-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0002_boatbooking_end_date_boatbooking_total_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boatreview',
            name='review_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
