# Generated by Django 4.1.1 on 2024-01-04 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0003_alter_boatreview_review_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='average_rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
