# Generated by Django 4.1.1 on 2024-01-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0004_alter_boat_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatbooking',
            name='confirm_booking',
            field=models.BooleanField(default=False),
        ),
    ]
