# Generated by Django 4.1.1 on 2024-01-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0006_boatbooking_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
