# Generated by Django 4.1.1 on 2024-01-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0007_boat_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='latitude',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='boat',
            name='longitude',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=10),
        ),
    ]
