# Generated by Django 4.1.1 on 2024-01-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0008_alter_boat_latitude_alter_boat_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='latitude',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='boat',
            name='longitude',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=12),
        ),
    ]
