# Generated by Django 4.1.1 on 2024-01-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_eventtickettype_total_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtickettype',
            name='total_ticket',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
