# Generated by Django 4.1.1 on 2024-01-03 16:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_eventtickettype_total_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='ticket_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=[], size=None),
            preserve_default=False,
        ),
    ]
