# Generated by Django 4.1.1 on 2024-01-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_eventbooking_ticket_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='confirm_booking',
            field=models.BooleanField(default=False),
        ),
    ]
