# Generated by Django 4.1.1 on 2024-01-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_event_location_alter_event_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='average_rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
