# Generated by Django 4.1.1 on 2024-01-07 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('event', '0008_alter_event_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwishlist',
            name='customer',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='customer_wishlist', to='customer.customer'),
            preserve_default=False,
        ),
    ]
