# Generated by Django 4.1.1 on 2024-01-07 19:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_userwishlist_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='ticket_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None),
        ),
    ]
