# Generated by Django 4.1.1 on 2024-01-01 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        ('customer', '0001_initial'),
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('longitude', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hotel_star', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('hotel_type', models.JSONField(blank=True, default=dict, null=True)),
                ('hotel_name', models.CharField(max_length=255)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('highlights', models.JSONField(blank=True, default=dict, null=True)),
                ('hotel_facilities', models.JSONField(blank=True, default=dict, null=True)),
                ('average_rating', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('hotel_services', models.JSONField(blank=True, default=dict, null=True)),
                ('latitude', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hotel_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_image', to='coreapp.document')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_hotel', to='vendor.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('room_type', models.IntegerField(default=0)),
                ('room_bed', models.IntegerField(default=0)),
                ('room_max_member', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('room_size', models.CharField(max_length=255)),
                ('room_max_child', models.IntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_hotel', to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('hotel_policies', models.JSONField(blank=True, default=dict, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_hotel', to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('review_time', models.DateTimeField(auto_now_add=True)),
                ('review', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_review_hotel', to='customer.customer')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_hotel', to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_hotel', to='hotel.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_pricing_hotel', to='hotel.room')),
            ],
        ),
        migrations.CreateModel(
            name='HotelFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('faq', models.JSONField(blank=True, default=dict, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_hotel', to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('booking_number', models.IntegerField()),
                ('quantity', models.IntegerField(default=0)),
                ('check_out', models.DateTimeField()),
                ('check_in', models.DateTimeField()),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_booking_hotel', to='customer.customer')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_hotel', to='hotel.hotel')),
            ],
        ),
    ]
