# Generated by Django 4.1.1 on 2024-01-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='room_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
