# Generated by Django 4.1.1 on 2024-01-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotelbooking_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelpricing',
            name='extra_price',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='hotelpricing',
            name='fixed_price',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
