# Generated by Django 4.1.1 on 2024-01-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotelpricing_extra_price_hotelpricing_fixed_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='confirm_booking',
            field=models.BooleanField(default=False),
        ),
    ]
