# Generated by Django 4.1.1 on 2024-01-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_hotelbooking_confirm_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='room_type',
            field=models.IntegerField(default=0),
        ),
    ]
