# Generated by Django 4.1.1 on 2024-01-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_hotel_location_alter_hotel_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='average_rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
