# Generated by Django 4.1.1 on 2024-01-03 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coreapp', '0002_user_role'),
        ('vendor', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('space_name', models.CharField(max_length=255)),
                ('amenities', models.JSONField(blank=True, default=dict, null=True)),
                ('latitude', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('average_rating', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('longitude', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('space_type', models.JSONField(blank=True, default=dict, null=True)),
                ('highlights', models.JSONField(blank=True, default=dict, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_space', to='vendor.vendor')),
                ('space_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_image', to='coreapp.document')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceTicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ticket_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpaceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('rating', models.IntegerField(default=0)),
                ('review', models.TextField()),
                ('review_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_review_space', to='customer.customer')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_space', to='space.space')),
            ],
        ),
        migrations.CreateModel(
            name='SpacePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('extra_price', models.JSONField(blank=True, default=dict, null=True)),
                ('fixed_price', models.JSONField(blank=True, default=dict, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_space', to='space.space')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_pricing_space', to='space.spacetickettype')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('faq', models.JSONField(blank=True, default=dict, null=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_space', to='space.space')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_bed', models.IntegerField(default=0)),
                ('total_bathroom', models.IntegerField(default=0)),
                ('max_people', models.IntegerField(default=0)),
                ('size', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_space', to='space.space')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('booking_number', models.IntegerField()),
                ('star_date', models.DateTimeField()),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('adult_quantity', models.IntegerField(default=1)),
                ('child_quantity', models.IntegerField(default=0)),
                ('end_date', models.DateTimeField()),
                ('adult_ticket_type', models.IntegerField()),
                ('child_ticket_type', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_booking_space', to='customer.customer')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_space', to='space.space')),
            ],
        ),
    ]
