# Generated by Django 4.1.1 on 2024-01-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacebooking',
            name='adult_ticket_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spacebooking',
            name='booking_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spacebooking',
            name='child_ticket_type',
            field=models.IntegerField(default=0),
        ),
    ]
