# Generated by Django 4.1.1 on 2024-01-03 18:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_alter_spacebooking_adult_ticket_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spacebooking',
            name='adult_quantity',
        ),
        migrations.RemoveField(
            model_name='spacebooking',
            name='adult_ticket_type',
        ),
        migrations.RemoveField(
            model_name='spacebooking',
            name='child_quantity',
        ),
        migrations.RemoveField(
            model_name='spacebooking',
            name='child_ticket_type',
        ),
        migrations.AddField(
            model_name='spacebooking',
            name='ticket_quantity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spacebooking',
            name='ticket_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=[], size=None),
            preserve_default=False,
        ),
    ]
