# Generated by Django 4.1.1 on 2024-01-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_remove_spacebooking_adult_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacebooking',
            name='confirm_booking',
            field=models.BooleanField(default=False),
        ),
    ]
