# Generated by Django 4.1.1 on 2024-01-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0005_space_location_alter_space_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='average_rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
